server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/auth/**
